# Generated by Django 3.2.16 on 2022-11-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='media/goods/')),
                ('descriptions', models.TextField()),
                ('condition', models.CharField(choices=[('NEW', 'NEW'), ('REFURBISHED', 'REFURBISHED')], max_length=40)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('position', models.CharField(choices=[('CEO', 'CEO'), ('CHAIRPERSON', 'CHAIRPERSON'), ('DEVELOPER', 'DEVELOPER'), ('SPONSOR', 'SPONSOR')], max_length=40)),
                ('person_image', models.ImageField(upload_to='media/people/')),
            ],
        ),
    ]
